name: CI with Custom MySQL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}    # <-- PAT 사용
          fetch-depth: 0            # 전체 히스토리 가져와야 커밋 푸시 시 충돌 방지
          persist-credentials: true # GITHUB_TOKEN으로 푸시 허용

      - name: Start MySQL container
        run: |
          docker run -d \
            --name mysql-test \
            -e MYSQL_DATABASE=test \
            -e MYSQL_ROOT_PASSWORD=pwroot \
            -e MYSQL_USER=test \
            -e MYSQL_PASSWORD=pwtest \
            -p 3800:3306 \
            mysql:8.0 \
            --default-authentication-plugin=mysql_native_password
      - name: Wait for MySQL to be ready
        run: |
          until docker exec mysql-test \
            mysqladmin ping -h127.0.0.1 \
            --silent --user=root --password=pwroot; do
            sleep 1
          done

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install mysql2

      - name: Fetch last lotto round & save JSON
        run: node page/fetch-last-game.js

      - name: Commit results.json back to repo
        env:
            PAT: ${{ secrets.PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add results.json lastGame.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: update json outputs (automated)"
            git push https://x-access-token:${PAT}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No JSON changes to commit"
          fi
