name: DB Setup, Seed & Read

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start MySQL service
        uses: mirromutth/mysql-action@v1.1
        with:
          'host port': 3800
          'container port': 3306
          'character set server': utf8
          'collation server': utf8_general_ci
          'mysql version': 8.0
          'mysql database': test
          'mysql root password': pwroot
          'mysql user': test
          'mysql password': pwtest

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping \
            --host=127.0.0.1 --port=3800 \
            --user=test --password="pwtest" --silent; do
            echo "Waiting for MySQL..."
            sleep 1
          done

      - name: Seed sample table & data
        run: |
          mysql \
            --host=127.0.0.1 --port=3800 \
            --user=test --password="pwtest" \
            -e "
              CREATE TABLE IF NOT EXISTS sample (
                id INT AUTO_INCREMENT PRIMARY KEY,
                name VARCHAR(50) NOT NULL
              );
              INSERT INTO sample (name) VALUES
                ('Alice'), ('Bob'), ('Charlie')
              ON DUPLICATE KEY UPDATE name=name;
            "

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install mysql2

      - name: Run sample DB reader
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3800
          DB_USER: test
          DB_PASSWORD: pwtest
          DB_NAME: test
        run: node page/read-db.js
