name: DB Setup and Crawl

# 1. 언제 실행할지 정의합니다.
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 2. 소스 코드를 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 3. MySQL Action 실행
      - name: Start MySQL service
        uses: mirromutth/mysql-action@v1.1
        with:
          'host port': 3800               # (키에 공백이 있으므로 따옴표로 감싸야 합니다)
          'container port': 3306
          'character set server': utf8
          'collation server': utf8_general_ci
          'mysql version': 8.0
          'mysql database': test
          'mysql root password': pwroot   # secrets 네임스페이스 사용
          'mysql user': test
          'mysql password': pwtest

      # 4. DB 접속 확인 (옵션)
      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping \
            --host=127.0.0.1 --port=3800 \
            --user=root --password="pwtest" --silent; do
            echo "Waiting for MySQL..."
            sleep 1
          done


