name: Fetch Lotto Results

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (write enabled)
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0
          persist-credentials: true

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore and build
        run: |
          dotnet restore
          dotnet build --configuration Release

      - name: Run fetcher
        run: |
          dotnet run --project FetchAllLottoResults.csproj --configuration Release

      - name: Commit generated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add allLottoResults.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: update page/allLottoResults.json (automated)"
            git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No changes to commit"
          fi
