name: DB Setup, Seed & Read

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start MySQL service
        uses: mirromutth/mysql-action@v1.1
        with:
          'host port': 3800
          'container port': 3306
          'character set server': utf8
          'collation server': utf8_general_ci
          'mysql version': 8.0
          'mysql database': test
          'mysql root password': pwroot
          'mysql user': test
          'mysql password': pwtest

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping \
            --host=127.0.0.1 --port=3800 \
            --user=root --password="pwroot" --silent; do
            echo "Waiting for MySQL..."
            sleep 1
          done

      - name: Force mysql_native_password authentication
        run: |
          mysql \
            --host=127.0.0.1 --port=3800 \
            --user=root --password="pwroot" \
            -e "
              ALTER USER 'test'@'%' 
                IDENTIFIED WITH mysql_native_password 
                BY 'pwtest';
              FLUSH PRIVILEGES;
            "

      - name: Seed sample table & data
        run: |
          mysql \
            --host=127.0.0.1 --port=3800 \
            --user=test --password="pwtest" \
            -e "
              CREATE TABLE IF NOT EXISTS sample (
                id INT AUTO_INCREMENT PRIMARY KEY,
                name VARCHAR(50) NOT NULL
              );
              INSERT INTO sample (name) VALUES
                ('Alice'), ('Bob'), ('Charlie')
              ON DUPLICATE KEY UPDATE name=name;
            "

      - name: Verify connection as test
        run: |
          mysql \
            --host=127.0.0.1 --port=3800 \
            --user=test --password="pwtest" \
            -e "
              SHOW TABLES;
              SELECT COUNT(*) AS total FROM sample;
            "
